spring: 
  profiles: 
    active: 
    - dev
    
--- 
##开发环境 数据库db_cloud01
server:
  port: 8001 
spring:
  profiles: dev  application:    name: microservicecloud-config-dept-provider
  datasource:    type: com.alibaba.druid.pool.DruidDataSource                     #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                      #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/db_cloud01?serverTimezone=UTC   #数据库名称
    username: root
    password: 123456
    dbcp2:      min-idle: 5                                                    #数据库连接池的最小维持连接数
      initial-size: 5                                                #初始化连接数
      max-total: 5                                                   #最大连接数
      max-wait-millis: 2000                                          #等待连接获取的最大超时时间    
eureka:  client:    service-url:
      #defaultZone: http://localhost:7001/eureka                      #单机eureka 注册中心地址
      defaultZone: http://eureka7001.com:7001/eureka
      #eureka集群，需要把服务同时注册进所有的注册中心  instance:    instance-id: microservicecloud-dept8001                          #修改服务入驻进eureka中的服务标识id，Status: localhost:microservicecloud-provider-dept:8001    prefer-ip-address: true                                          #localhost显示为ip地址，127.0.0.1

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml            #mybatis配置文件素在路径
  type-aliases-package: com.yhl.main.entities                   #所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                                #mapper映射文件位置 
info:
  app.name: microservicecloud-provider-dept-dev
  company.name: LEFENG
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
##测试环境  数据库db_cloud02
server:
  port: 8001 
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                     #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                      #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/db_cloud02?serverTimezone=UTC   #数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                                    #数据库连接池的最小维持连接数
      initial-size: 5                                                #初始化连接数
      max-total: 5                                                   #最大连接数
      max-wait-millis: 2000                                          #等待连接获取的最大超时时间    
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka                      #单机eureka 注册中心地址
      defaultZone: http://eureka7001.com:7001/eureka
      #eureka集群，需要把服务同时注册进所有的注册中心
  instance:
    instance-id: microservicecloud-dept8001                          #修改服务入驻进eureka中的服务标识id，Status: localhost:microservicecloud-provider-dept:8001
    prefer-ip-address: true                                          #localhost显示为ip地址，127.0.0.1
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml                 #mybatis配置文件素在路径
  type-aliases-package: com.yhl.main.entities                        #所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  
info:
  app.name: microservicecloud-provider-dept-test
  company.name: LEFENG
  build.artifactId: $project.artifactId$
  build.version: $project.version$  